### PR TITLE
Add forget password and sendgrid email

### PR DESCRIPTION
**Pull request by mahi25soni**
I have tried to add forget password using sendgrid mail service.

### CODE REVIEW

**Review by arpittyagi102 — APPROVED** [review]
Hey @mahi25soni, Thank you so much for your contribution, I am merging this pull request.
Please give this repository a star 🌟

**Comment by arpittyagi102** [comment]
hey @mahi25soni, I am not able to create a sendgrid account to retrieve API keys.
every time i try to create the account it is getting blocked by send grid
> Hello Account Holder,
We have reviewed your account and have determined that Twilio’s services cannot support your account at this time due to one or more of the following:
Violations of [Acceptable Use Policy](https://www.twilio.com/legal/aup)
Violations of [Twilio SendGrid Email Policy](https://www.twilio.com/legal/service-country-specific-terms/email)
Accounts with unresolved billing issues
Inability to verify provided information
Thank you for your interest in Twilio SendGrid, best of luck with your future endeavors.

Will you please help me in that !!

**Comment by mahi25soni** [comment]
@arpittyagi102 Let me check SendGrid problem

**Comment by arpittyagi102** [comment]
Hello @mahi25soni, any update?

**Review by arpittyagi102 — COMMENTED** [review]
Are you still working on it or can i delete this pull request

**Pull request closed without merging**
