### PR TITLE
Add Login & Signup Submission Result Alert

### PR DESCRIPTION
**Pull request by moonlight0301**
Add a notification in the top right corner of the login interface to provide feedback to the user about the submission result.
### Changes Made:
Added a notification box in the top right corner of the login interface to display the submission result. Dynamically update the text and styling of the notification box based on the submission result.
### Expected Behavior:
- When the user successfully submits the login form, display a success message in the notification box.
image
- When the user fails to log in or submits incorrect form data, display a failure message in the notification box and guide the user to check their credentials.
image
image
image

### CODE REVIEW

**Review by arpittyagi102 — APPROVED** [review]
Hey @moonlight0301,
for some reason i am not able to see the warnings,
have a look at pulll request preview [https://link-up-git-fork-saagarjha1-master-arpittyagirocks.vercel.app/](https://link-up-git-fork-saagarjha1-master-arpittyagirocks.vercel.app/)
Tell me if i am doing something wrong

**Comment by arpittyagi102** [comment]
Hey, Thank you so much, This is amazing !!
Will you be able to add the same on Sign up page too.
Also i would love it, if its on top-center instead of top-right

**Review by arpittyagi102 — APPROVED** [review]
Hey, Thank you so much, This is amazing !!
Will you be able to add the same on Sign up page too.
Also i would love it, if its on top-center instead of top-right

**Comment by moonlight0301** [comment]
Thank you! I will try changing the location of the login page alert to the top center first.

**Comment by moonlight0301** [comment]
I have completed this change.
image
image

**Comment by moonlight0301** [comment]
Now, I add the same on Sign up page. If I do something wrong, please tell me to change it.
image
image
image

**Review by arpittyagi102 — APPROVED** [review]
Hello @moonlight0301, Thank you so much for your contribution

**Pull request merged**
