### PR TITLE
Added "Already have an account" link to the sign-up page #11

### PR DESCRIPTION
**Pull request by moonlight0301**
The purpose of this pull request is to add an "Already have an account" link to our sign-up page, providing users with a convenient way to navigate to the login page. This link will be placed below the sign-up form, assisting users in quickly finding the option to log in.
To achieve this goal, the following changes have been made:

- Added a new hyperlink at the bottom of the sign-up page with the text "Already have an account log in"

- Set the target URL of the link to the login page to ensure that users are redirected to the login page upon clicking the link.

The purpose of this change is to enhance the user experience and provide users with more options and flexibility during the sign-up process.
### **screen shot**

- before
image
- after
image

### CODE REVIEW

**Review by arpittyagi102 — APPROVED** [review]
Hey, Thank you so much for your contribution, I am merging this PR
please give this repository a star 🌟

**Review by arpittyagi102 — COMMENTED** [review]
Hey @moonlight0301, i think you forgot to add
```bash
import { Link } from react-router-dom
```
### The code is showing this error on vercel :
```bash
12:57:13.000 | Failed to compile.
12:57:13.001 | [eslint]
12:57:13.001 | src/Pages/SignupPage/SignupPage.jsx
12:57:13.001 | Line 151:38:  'Link' is not defined  react/jsx-no-undef
12:57:13.001 |  
12:57:13.001 | Search for the keywords to learn more about each error.
12:57:13.001 |  
12:57:13.002 |  
12:57:13.042 | Error: Command "npm run build" exited with 1
```

**Review by moonlight0301 — COMMENTED** [review]
Thank you for pointing my mistake. I have changed the file.

**Review by arpittyagi102 — APPROVED** [review]
Thank you, All done

**Pull request merged**
