### PR TITLE
added a "already have an account" btn

### PR DESCRIPTION
**Pull request by anubhav1206**

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
Hey, What i want is "Already have a account" should be a link, which looks like "Don't have an account" link on Login page and clicking on which it should go to "/login"
clicking on your button it is trying to submit the form

**Comment by anubhav1206** [comment]
> Hey, What i want is "Already have a account" should be a link, which looks like "Don't have an account" link on Login page and clicking on which it should go to "/login" clicking on your button it is trying to submit the form

will make the necesary changes

**Comment by anubhav1206** [comment]
I have made the changes from my end, however, I am unable to run it locally. Can you check the changes and let me know?

**Comment by arpittyagi102** [comment]
### It is showing an error 
```bash
21:59:12.548 | Failed to compile.
--
21:59:12.548 |  
21:59:12.548 | [eslint]
21:59:12.548 | src/Pages/SignupPage/SignupPage.jsx
21:59:12.549 | Line 150:41:  'Link' is not defined  react/jsx-no-undef
21:59:12.549 |  
21:59:12.549 | Search for the keywords to learn more about each error.
21:59:12.549 |  
21:59:12.549 |  
21:59:12.596 | Error: Command "npm run build" exited with 1
21:59:12.828 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

May i ask why are you not able to run it locally...

**Review by arpittyagi102 — COMMENTED** [review]
I am closing the pull request as the issue has been solved

**Pull request closed without merging**
