### PR TITLE
added OneTapGoogleLogin

### PR DESCRIPTION
**Pull request by Vyom-V**
faced issue with frontend env file
added another button "quick login" with google symbol which implements oneTap feat

Do let me know for any changes

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
Sorry for the inconvenience about the env file,
As per the standards, insteading of adding a button, trigger the onetap login after 3 seconds after page load, if you can

**Comment by Vyom-V** [comment]
Definitely, could you help me a bit with the .env file setup in frontend?
I managed to get the backend connected with my mongoDb URI but just creating an .env file in the front-end folder doesnt seem to be working , could be able to provide me with some reference code.,thanks

**Comment by arpittyagi102** [comment]
Hey, you should try putting dummy variable in the enviroment variables. that may help
for example
```bash
const value = process.env.SECRET || "DUMMYVALUE"
```
this may solve the problem, if it doesn't, let me know

**Comment by Vyom-V** [comment]
implemented it.
image

a change I had to do was in index.js  `<GoogleOAuthProvider clientId={clientId}>`
as directly passing client_id to useGoogleOneTapLogin wasnt wokring so I looked into implementation of useGoogleOneTapLogin which was getting client_id from context of GoogleOAuthProvider

Couldn't do the onLoad feature as useGoogleOneTapLogin is a hook and react doesn't allow hooks in useEffect
Do let me if you have any idea about the implementation of onLoad

**Review by arpittyagi102 — APPROVED** [review]
Hey, Thank you for your contribution, I am merging this PR
Please give this repository a star 🌟

**Pull request merged**
