### PR TITLE
added Lazy Loading in frontend

### PR DESCRIPTION
**Pull request by rohitrokz29**
Added React Lazy loaders and fallback component

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
Hello @rohitrokz29, Thank you for the contribution. We are reviewing your pull request.

**Comment by rohitrokz29** [comment]
Yes I would do it.

**Comment by rohitrokz29** [comment]
Yes I will do it.

**Comment by rohitrokz29** [comment]
Hey I have added the loader in the friends list section. Please check it.

**Review by arpittyagi102 — COMMENTED** [review]
Thank you for the changes, We are reviewing the request

**Review by arpittyagi102 — APPROVED** [review]
Hello @rohitrokz29, Thank you so much for your contribution.
I am merging this pull request

**Comment by rohitrokz29** [comment]
Thank you

**Pull request merged**
